//------------------------------------------------------------------------
// Copyright(c) 2024 fhw.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Synth.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Synth VST3 (64Bit)"
#else
#define stringFileDescription	"Synth VST3"
#endif
#define stringCompanyName		"fhw\0"
#define stringLegalCopyright	"Copyright(c) 2024 fhw."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
